version: "3.9"

services:
  bot:
    build: .
    image: weather_bot:latest
    container_name: weather_bot
    restart: always
    environment:
      BOT_TOKEN: <токен бота без ковычек>
      WEATHER_SOURCE: https://meteo7.ru/forecast/
      POSTGRES_PASSWORD: weather_bot
      POSTGRES_USER: weather_bot
      POSTGRES_DB: weather_bot
      DATABASE_HOST: weather_bot_db
      DATABASE_PORT: 5432

    depends_on:
      - weather_bot_db
    networks:
      - weathe_bot_network

  weather_bot_db:
    image: postgres:latest
    container_name: weather_bot_db
    restart: always
    volumes:
      # инициализируем создание необходимых таблиц и данных в БД
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      # создаем внешнее хранилище данных для БД
      - postgres_data_weather_bot:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: weather_bot
      POSTGRES_USER: weather_bot
      POSTGRES_DB: weather_bot
      # порт target обязательно должен быть 5432, т.к. это порт ДБ внутри контейнера
      # наружу выставлен порт 5434 для избегания конфликтов с локальной ДБ
    ports:
      - "5434:5432"
    networks:
      - weathe_bot_network

networks:
  weathe_bot_network:
    name: weathe_bot_network
    driver: bridge

volumes:
  postgres_data_weather_bot:
